-- -*-lua-*-
-- LDoc configuraiton file
project  = 'Luasched API'
--description = "Luasched API"
dir      = "doc"
title    = 'Luasched API'
format   = 'markdown'
style    = "doc"
template = "doc"
file     = {
    "log/init.lua",
    "sched/init.lua",
    --"sched/platform.lua",
    --"sched/lock.lua",
    --"sched/pipe.lua",
    --"shell/telnet.lua",
    "c/checks.c",
    --"socket/platform.lua",
    "utils/table.lua",
    "utils/path.lua",
    "utils/ltn12/source.lua",
}
